name: RookieAirDrops
version: '1.0-SNAPSHOT'
main: com.cuzz.rookieairdrops.RookieAirDrops
api-version: '1.21'
depend: [ModelEngine, Oraxen]
commands:
  airdrop:
    description: Spawn a hot air balloon airdrop
    usage: /<command> [spawn]
